server:
  port: 10000
spring:
  application:
    name: tanhua-today
  data:
    mongodb:
#      host: 127.0.0.1
#      port: 27017
      uri: mongodb://tanhua:tanhua@127.0.0.1:27017/tanhua
#      username: tanhua
#      password: tanhua
#      database: tanhua
  main:
    allow-bean-definition-overriding: true
